/*Copyright (C) 2019 Jannis Horn - All Rights Reserved
 *You may use, distribute and modify this code under the
 *terms of the GNU GENERAL PUBLIC LICENSE Version 3.
 */

extern "C" {
  #define PY_SSIZE_T_CLEAN
  #include "Python.h"
  #include "structmember.h"
}

#include "c_graph.h"
#include "c_graph_node.h"

extern "C"
{

static struct PyModuleDef _c_graph_interface_module = {
  PyModuleDef_HEAD_INIT,
  "_c_graph_interface",
  "Interface allowing to access data in graph objects generated by ExtractGraph",
  -1,
  nullptr, nullptr, nullptr, nullptr, nullptr
};


PyMODINIT_FUNC PyInit__c_graph_interface( void )
{
  PyObject* py_mod;

  if( PyType_Ready( &PyCGraphType ) < 0 )
    return nullptr;
  if( PyType_Ready( &PyCGraphNodeType ) < 0 )
    return nullptr;

  py_mod = PyModule_Create( &_c_graph_interface_module );
  if( py_mod == nullptr )
    return nullptr;

  Py_INCREF( &PyCGraphType );
  PyModule_AddObject( py_mod, "CGraph", (PyObject*)&PyCGraphType );
  Py_INCREF( &PyCGraphNodeType );
  PyModule_AddObject( py_mod, "CGraphNode", (PyObject*)&PyCGraphNodeType );

  return py_mod;
}

}
